# Generated by Django 6.0.4 on 2026-06-25 02:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudConsulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=50)),
                ('correo_electronico', models.EmailField(max_length=254)),
                ('tipo_consulta_cliente', models.CharField(choices=[('mesa', 'Reserva de Mesa'), ('evento', 'Evento Privado'), ('general', 'Consulta General')], default='general', max_length=20)),
                ('fecha_reserva', models.DateField(blank=True, null=True)),
                ('cantidad_personas', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('mensaje', models.TextField()),
                ('categoria_asignada', models.CharField(default='General', max_length=50)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioPermitido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('codigo_validation', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroConsulta',
            fields=[
            ],
            options={
                'verbose_name': 'Consulta General',
                'verbose_name_plural': 'CONSULTAS GENERALES',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('mi_app.solicitudconsulta',),
        ),
        migrations.CreateModel(
            name='RegistroEvento',
            fields=[
            ],
            options={
                'verbose_name': 'Evento Privado',
                'verbose_name_plural': 'EVENTOS PRIVADOS',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('mi_app.solicitudconsulta',),
        ),
        migrations.CreateModel(
            name='RegistroReserva',
            fields=[
            ],
            options={
                'verbose_name': 'Reserva de Mesa',
                'verbose_name_plural': 'RESERVAS DE MESAS',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('mi_app.solicitudconsulta',),
        ),
    ]
