# Generated by Django 6.0.4 on 2026-07-28 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContenidoInicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_principal', models.CharField(default='ECLIPSE NIGHTCLUB', max_length=200)),
                ('subtitulo', models.CharField(default='LA MEJOR EXPERIENCIA NOCTURNA', max_length=200)),
                ('texto_bienvenida', models.TextField(default='Bienvenido al club nocturno más exclusivo de la ciudad. Disfruta de la mejor música, DJs en vivo y una atmósfera inigualable.')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contenido de Inicio',
                'verbose_name_plural': 'Contenido de Inicio',
            },
        ),
    ]
