# Generated by Django 6.0.4 on 2026-06-25 00:47

from django.db import migrations


def cargar_cliente_propietario(apps, schema_editor):
    UsuarioPermitido = apps.get_model('mi_app', 'UsuarioPermitido')

    UsuarioPermitido.objects.get_or_create(
        email="annavillegas@live.com.ar",
        defaults={
            "nombre": "Anna Villegas",
            "codigo_validation": "ECLIPSE2026"
        }
    )


def revertir_carga(apps, schema_editor):
    UsuarioPermitido = apps.get_model('mi_app', 'UsuarioPermitido')
    UsuarioPermitido.objects.filter(email="annavillegas@live.com.ar").delete()

class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(cargar_cliente_propietario, revertir_carga),
    ]
